# Generated by Django 3.2.4 on 2021-07-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='naickname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
