# Generated by Django 3.2.4 on 2021-07-07 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_naickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='naickname',
        ),
    ]
