# Generated by Django 3.2.4 on 2021-06-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='limited_products',
            field=models.BooleanField(default=False),
        ),
    ]
