# Generated by Django 3.2.4 on 2021-07-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_limited_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varation',
            name='PRDIMG',
        ),
        migrations.RemoveField(
            model_name='varation',
            name='PRDName',
        ),
        migrations.AddField(
            model_name='varation',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='varation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='varation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='varation',
            name='variation_vale',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
