# Generated by Django 3.2.4 on 2021-06-16 20:56

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210616_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_img',
            name='PRDImg',
            field=models.ImageField(upload_to=product.models.image_upoad_to),
        ),
    ]
