# Generated by Django 3.2.4 on 2021-06-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_varation_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varation_img',
            name='PRDIMG',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
