# Generated by Django 3.2.4 on 2021-06-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_varation_img_prdimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='varation_img',
            name='PRDName',
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
    ]
