# Generated by Django 3.2.4 on 2021-07-14 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_variation_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_order',
            field=models.BooleanField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('default', 'default'), ('Pending', 'Pending'), ('Under_Process', 'Under_Process'), ('Completed', 'Completed'), ('Canceld', 'Canceld'), ('Rejected', 'Rejected')], default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_at',
            field=models.DateTimeField(max_length=100),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(max_length=100)),
                ('product_price', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(max_length=100)),
                ('update_at', models.DateTimeField(max_length=100)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.variation')),
            ],
        ),
    ]
