# Generated by Django 3.2.4 on 2021-07-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210717_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='i_agree',
            field=models.BooleanField(default=False),
        ),
    ]
