# Generated by Django 3.2.4 on 2021-06-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
