# Generated by Django 3.2.4 on 2021-06-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitems_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
