# Generated by Django 3.2.4 on 2021-06-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitems_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='is_active',
        ),
    ]
